# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_genre', models.CharField(max_length=200)),
                ('book_short_desc', models.TextField()),
                ('book_size', models.BigIntegerField()),
                ('parent_site_id', models.IntegerField()),
                ('cached_book_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Books_2_users',
            fields=[
                ('books_2_users_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cached_books',
            fields=[
                ('cached_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_link', models.CharField(max_length=100)),
                ('book_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('header_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_name', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=100, unique=True)),
                ('site_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='books_2_users',
            unique_together=set([('book_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='books',
            unique_together=set([('book_id', 'parent_site_id'), ('book_id', 'cached_book_id')]),
        ),
    ]
