# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_secret_key',
            field=models.CharField(default='qwerty', max_length=100),
            preserve_default=False,
        ),
    ]
