# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_users_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_secret_key',
            field=models.CharField(default='qwerty', max_length=100),
        ),
    ]
